### ISSUE TITLE
Bootstrap / Blacklight Cleanup

### ISSUE THREAD

**Issue by adjam** [trln/trln_argon#357]
No doubt we missed a few things that changed in Bootstrap and Blacklight in releasing [v2.0.0](d9997af3878fa323812473a385581a0376de212a) so this is a blanket issue for all that stuff.  Please create PRs against the `develop` branch and reference this issue number `#357` in your commit messages.

**Comment by adjam** [comment]
see e.g. #356

**Comment by kellysmithfarrell** [comment]
#359

**Comment by kellysmithfarrell** [comment]
#361

**Comment by kellysmithfarrell** [comment]
#362

**Comment by adjam** [comment]
I think we can call this closed at this point, anything else that crops up can be handled on its own.
